/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AnalysisApi,
  ApplicantApi,
  AuditTrailEventApi,
  CheckApi,
  HealthApi,
  ImageApi,
  InspectionApi,
  NoteApi,
  TagApi,
  TokenApi,
  TransactionApi,
  VASPApi,
  WebSDKLinkApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { SumsubCustom } from "./client-custom";

export class Sumsub extends SumsubCustom {
  readonly analysis: AnalysisApi;
  readonly applicant: ApplicantApi;
  readonly auditTrailEvent: AuditTrailEventApi;
  readonly check: CheckApi;
  readonly health: HealthApi;
  readonly image: ImageApi;
  readonly inspection: InspectionApi;
  readonly note: NoteApi;
  readonly tag: TagApi;
  readonly token: TokenApi;
  readonly transaction: TransactionApi;
  readonly vASP: VASPApi;
  readonly webSDKLink: WebSDKLinkApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.analysis = new AnalysisApi(configuration);
    this.applicant = new ApplicantApi(configuration);
    this.auditTrailEvent = new AuditTrailEventApi(configuration);
    this.check = new CheckApi(configuration);
    this.health = new HealthApi(configuration);
    this.image = new ImageApi(configuration);
    this.inspection = new InspectionApi(configuration);
    this.note = new NoteApi(configuration);
    this.tag = new TagApi(configuration);
    this.token = new TokenApi(configuration);
    this.transaction = new TransactionApi(configuration);
    this.vASP = new VASPApi(configuration);
    this.webSDKLink = new WebSDKLinkApi(configuration);
  }

}
