/* tslint:disable */
/* eslint-disable */
/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AnalysisStandaloneCryptoInitiationRequest } from '../models';
// @ts-ignore
import { AnalysisStandaloneCryptoInitiationRequest1 } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * AnalysisApi - axios parameter creator
 * @export
 */
export const AnalysisApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Initiates standalone crypto analysis.
         * @summary Standalone crypto analysis
         * @param {AnalysisStandaloneCryptoInitiationRequest} [analysisStandaloneCryptoInitiationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        standaloneCryptoInitiation: async (analysisStandaloneCryptoInitiationRequest?: AnalysisStandaloneCryptoInitiationRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/resources/standalone/crypto/cryptoSourceOfFunds`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();
            const addFormParam = async (name: string, data: any, isBinary: boolean, isPrimitiveType: boolean) => {
                if (isBinary) {
                    if (data instanceof Uint8Array) {
                        // Handle Buffer data
                        const filetype = await fromBuffer(data)
                        const filename = filetype === undefined ? name : `${name}.${filetype.ext}`
                        localVarFormParams.append(name, data as any, filename);
                    } else if ("name" in data) {
                        // File instances in browsers and Node.js have the
                        // "name" property "Duck typing" files to handle browser
                        // File class or Node.js File class
                        // Web: https://developer.mozilla.org/en-US/docs/Web/API/File
                        // Node.js: https://nodejs.org/api/buffer.html#new-bufferfilesources-filename-options
                        if (isBrowser()) {
                            // FormData in browser can accept File/Blob directly
                            localVarFormParams.append(name, data, data.name);
                        } else {
                            // FormData in Node.js can only accept raw Buffer so convert before passing
                            const bytes = await data.arrayBuffer()
                            const buffer = Buffer.from(bytes)
                            localVarFormParams.append(name, buffer, data.name);
                        }
                    }
                } else {
                    if (isPrimitiveType) {
                        /**
                         * FormData can only accept string or Blob so we need to convert
                         * non-string primitives to string. We also need to convert
                         */
                        if (typeof data === "object") {
                          localVarFormParams.append(name, JSON.stringify(data));
                        } else {
                          localVarFormParams.append(name, data);
                        }
                    } else {
                        if (isBrowser()) {
                            localVarFormParams.append(name, new Blob([JSON.stringify(data)], { type: "application/json" }))
                        } else {
                            localVarFormParams.append(name, JSON.stringify(data), { type: "application/json", filename: "data.json" });
                        }
                    }
                }
            }
            if (!isBrowser()) Object.assign(localVarHeaderParameter, localVarFormParams.getHeaders());

            // authentication sec0 required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "X-App-Token", keyParamName: "sec0", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;
            requestBeforeHook({
                requestBody: analysisStandaloneCryptoInitiationRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/resources/standalone/crypto/cryptoSourceOfFunds',
                httpMethod: 'POST'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AnalysisApi - functional programming interface
 * @export
 */
export const AnalysisApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AnalysisApiAxiosParamCreator(configuration)
    return {
        /**
         * Initiates standalone crypto analysis.
         * @summary Standalone crypto analysis
         * @param {AnalysisApiStandaloneCryptoInitiationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async standaloneCryptoInitiation(requestParameters: AnalysisApiStandaloneCryptoInitiationRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const analysisStandaloneCryptoInitiationRequest: AnalysisStandaloneCryptoInitiationRequest = {
                currency: requestParameters.currency,
                direction: requestParameters.direction,
                txn: requestParameters.txn,
                address: requestParameters.address,
                tokenId: requestParameters.tokenId
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.standaloneCryptoInitiation(analysisStandaloneCryptoInitiationRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AnalysisApi - factory interface
 * @export
 */
export const AnalysisApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AnalysisApiFp(configuration)
    return {
        /**
         * Initiates standalone crypto analysis.
         * @summary Standalone crypto analysis
         * @param {AnalysisApiStandaloneCryptoInitiationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        standaloneCryptoInitiation(requestParameters: AnalysisApiStandaloneCryptoInitiationRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.standaloneCryptoInitiation(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for standaloneCryptoInitiation operation in AnalysisApi.
 * @export
 * @interface AnalysisApiStandaloneCryptoInitiationRequest
 */
export type AnalysisApiStandaloneCryptoInitiationRequest = {
    
} & AnalysisStandaloneCryptoInitiationRequest

/**
 * AnalysisApiGenerated - object-oriented interface
 * @export
 * @class AnalysisApiGenerated
 * @extends {BaseAPI}
 */
export class AnalysisApiGenerated extends BaseAPI {
    /**
     * Initiates standalone crypto analysis.
     * @summary Standalone crypto analysis
     * @param {AnalysisApiStandaloneCryptoInitiationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnalysisApiGenerated
     */
    public standaloneCryptoInitiation(requestParameters: AnalysisApiStandaloneCryptoInitiationRequest, options?: AxiosRequestConfig) {
        return AnalysisApiFp(this.configuration).standaloneCryptoInitiation(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
