/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApplicantSubmitTransactionDataRequestApplicantIdDocsInner
 */
export interface ApplicantSubmitTransactionDataRequestApplicantIdDocsInner {
    /**
     * A [document type](ref:add-id-documents#supported-document-types).
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantIdDocsInner
     */
    'idDocType'?: string;
    /**
     * Date of birth (format YYYY-mm-dd, e.g. 2001-09-25).
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantIdDocsInner
     */
    'dob'?: string;
    /**
     * Birthplace.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantIdDocsInner
     */
    'placeOfBirth'?: string;
    /**
     * Alpha-3 country code of the provided document.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantIdDocsInner
     */
    'country'?: string;
    /**
     * A document number.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantIdDocsInner
     */
    'number'?: string;
}

