/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApplicantChangeExtractedInfoRequest
 */
export interface ApplicantChangeExtractedInfoRequest {
    /**
     * The first name of the applicant.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest
     */
    'firstName'?: string;
    /**
     * The last name of the applicant.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest
     */
    'lastName'?: string;
    /**
     * The middle name of the applicant.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest
     */
    'middleName'?: string;
    /**
     * Legal name.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest
     */
    'legalName'?: string;
    /**
     * An applicant gender (`M` or `F`).
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest
     */
    'gender'?: string;
    /**
     * Applicant date of birth (format `YYYY-mm-dd`, e.g. 2001-09-25).
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest
     */
    'dob'?: string;
    /**
     * The applicant birthplace.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest
     */
    'placeOfBirth'?: string;
    /**
     * Applicant country of birth.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest
     */
    'countryOfBirth'?: string;
    /**
     * Applicant state of birth.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest
     */
    'stateOfBirth'?: string;
    /**
     * Alpha-3 country code (e.g. `DEU` or `GBR`).
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest
     */
    'country'?: string;
    /**
     * Alpha-3 country code.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest
     */
    'nationality'?: string;
    /**
     * List of applicant addresses.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest
     */
    'addresses'?: string;
    /**
     * Tax identification number.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest
     */
    'tin'?: string;
}

