/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApplicantSandboxVerificationResponseRequest1
 */
export interface ApplicantSandboxVerificationResponseRequest1 {
    /**
     * A `GREEN` or `RED` label under which you want to simulate the response. For more information, see [this article](https://docs.sumsub.com/reference).
     * @type {string}
     * @memberof ApplicantSandboxVerificationResponseRequest1
     */
    'reviewAnswer': string;
    /**
     * An array of [rejection labels](/docs/receive-and-interpret-results-via-api#understand-rejection).
     * @type {Array<string>}
     * @memberof ApplicantSandboxVerificationResponseRequest1
     */
    'rejectLabels': Array<string>;
    /**
     * A `FINAL` or `RETRY` rejection type indicating whether a rejection should be final or temporary.
     * @type {string}
     * @memberof ApplicantSandboxVerificationResponseRequest1
     */
    'reviewRejectType'?: string;
    /**
     * A rejection comment that should not be available to your applicants.
     * @type {string}
     * @memberof ApplicantSandboxVerificationResponseRequest1
     */
    'clientComment'?: string;
    /**
     * A comment that supposed to be shown to the applicant, explaining the reason of rejection.
     * @type {string}
     * @memberof ApplicantSandboxVerificationResponseRequest1
     */
    'moderationComment'?: string;
}

