/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApplicantImportCompletedRequestReviewReview } from './applicant-import-completed-request-review-review';

/**
 * Review results
 * @export
 * @interface ApplicantImportCompletedRequestReview
 */
export interface ApplicantImportCompletedRequestReview {
    /**
     * Date of users\' creation on your side in a format: \"2022-11-21 08:25:32+0000\"
     * @type {string}
     * @memberof ApplicantImportCompletedRequestReview
     */
    'createDate'?: string;
    /**
     * review date on your side in a format: \"2022-11-21 08:25:32+0000\"
     * @type {string}
     * @memberof ApplicantImportCompletedRequestReview
     */
    'reviewDate'?: string;
    /**
     * 
     * @type {ApplicantImportCompletedRequestReviewReview}
     * @memberof ApplicantImportCompletedRequestReview
     */
    'review'?: ApplicantImportCompletedRequestReviewReview;
    /**
     * \"completed\"
     * @type {string}
     * @memberof ApplicantImportCompletedRequestReview
     */
    'reviewStatus'?: string;
}

