/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApplicantCreateActionRequestPaymentMethodData } from './applicant-create-action-request-payment-method-data';

/**
 * 
 * @export
 * @interface ApplicantAddPaymentMethodInformationRequest
 */
export interface ApplicantAddPaymentMethodInformationRequest {
    /**
     * A payment type. Can be: `bankCard`, `eWallet`, `wireTransfer`.
     * @type {string}
     * @memberof ApplicantAddPaymentMethodInformationRequest
     */
    'type': string;
    /**
     * A payment subtype. For example, `VISA`, `MASTERCARD`, etc.
     * @type {string}
     * @memberof ApplicantAddPaymentMethodInformationRequest
     */
    'subType'?: string;
    /**
     * 
     * @type {ApplicantCreateActionRequestPaymentMethodData}
     * @memberof ApplicantAddPaymentMethodInformationRequest
     */
    'data'?: ApplicantCreateActionRequestPaymentMethodData;
}

