/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Additional fixed information related to a payment source.
 * @export
 * @interface ApplicantCreatePaymentSourceActionsRequestPaymentSourceFixedInfo
 */
export interface ApplicantCreatePaymentSourceActionsRequestPaymentSourceFixedInfo {
    /**
     * A unique identifier for an account (e.g., \"123456\").
     * @type {string}
     * @memberof ApplicantCreatePaymentSourceActionsRequestPaymentSourceFixedInfo
     */
    'accountIdentifier'?: string;
    /**
     * An email address associated with a particular account.
     * @type {string}
     * @memberof ApplicantCreatePaymentSourceActionsRequestPaymentSourceFixedInfo
     */
    'email'?: string;
    /**
     * The full name of an account holder (e.g., \"Alex Kim\").
     * @type {string}
     * @memberof ApplicantCreatePaymentSourceActionsRequestPaymentSourceFixedInfo
     */
    'fullName'?: string;
    /**
     * A name of the financial institution where an account is held (e.g., Revolut).
     * @type {string}
     * @memberof ApplicantCreatePaymentSourceActionsRequestPaymentSourceFixedInfo
     */
    'institutionName'?: string;
}

