/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApplicantChangeExtractedInfoRequest1
 */
export interface ApplicantChangeExtractedInfoRequest1 {
    /**
     * The first name of the applicant.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest1
     */
    'firstName'?: string;
    /**
     * The last name of the applicant.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest1
     */
    'lastName'?: string;
    /**
     * The middle name of the applicant.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest1
     */
    'middleName'?: string;
    /**
     * Legal name.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest1
     */
    'legalName'?: string;
    /**
     * An applicant gender (`M` or `F`).
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest1
     */
    'gender'?: string;
    /**
     * Applicant date of birth (format `YYYY-mm-dd`, e.g. 2001-09-25).
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest1
     */
    'dob'?: string;
    /**
     * The applicant birthplace.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest1
     */
    'placeOfBirth'?: string;
    /**
     * Applicant country of birth.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest1
     */
    'countryOfBirth'?: string;
    /**
     * Applicant state of birth.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest1
     */
    'stateOfBirth'?: string;
    /**
     * Alpha-3 country code (e.g. `DEU` or `GBR`).
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest1
     */
    'country'?: string;
    /**
     * Alpha-3 country code.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest1
     */
    'nationality'?: string;
    /**
     * List of applicant addresses.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest1
     */
    'addresses'?: string;
    /**
     * Tax identification number.
     * @type {string}
     * @memberof ApplicantChangeExtractedInfoRequest1
     */
    'tin'?: string;
}

