/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApplicantChangeCompanyDataRequest1
 */
export interface ApplicantChangeCompanyDataRequest1 {
    /**
     * Name of the company.
     * @type {string}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'companyName': string;
    /**
     * Registration number.
     * @type {string}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'registrationNumber': string;
    /**
     * A three-letter country code (e.g. `DEU`).
     * @type {string}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'country'?: string;
    /**
     * Legal name.
     * @type {string}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'legalAddress'?: string;
    /**
     * Date of incorporation (format `YYYY-mm-dd`, e.g. 2001-09-25).
     * @type {string}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'incorporatedOn'?: string;
    /**
     * Type of entity.
     * @type {string}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'type'?: string;
    /**
     * Email address.
     * @type {string}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'email'?: string;
    /**
     * Description of the control scheme of the group of entities.
     * @type {string}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'controlScheme'?: string;
    /**
     * Phone number.
     * @type {string}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'phone'?: string;
    /**
     * Taxpayer registration number/Code of taxpayer registration.
     * @type {string}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'taxId'?: string;
    /**
     * Location of registration.
     * @type {string}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'registrationLocation'?: string;
    /**
     * Website\'s URL.
     * @type {string}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'website'?: string;
    /**
     * Postal address.
     * @type {string}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'postalAddress'?: string;
    /**
     * Contains applicantIds of beneficiaries and additional info like position and type.
     * @type {Array<string>}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'beneficiaries'?: Array<string>;
    /**
     * List of addresses.
     * @type {Array<string>}
     * @memberof ApplicantChangeCompanyDataRequest1
     */
    'addresses'?: Array<string>;
}

