/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the payment method.
 * @export
 * @interface ApplicantSubmitTransactionDataRequestApplicantPaymentMethod
 */
export interface ApplicantSubmitTransactionDataRequestApplicantPaymentMethod {
    /**
     * Payment method type: `card`/`account`/`crypto`.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantPaymentMethod
     */
    'type'?: string;
    /**
     * Representation of the account ID: Account number, IBAN or DC hash for `card`, crypto wallet address for `crypto` type etc.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantPaymentMethod
     */
    'accountId'?: string;
    /**
     * The payment issuing country code in Alpha-3 format.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantPaymentMethod
     */
    'issuingCountry'?: string;
    /**
     * Indication of 3d secure auth being used.
     * @type {boolean}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantPaymentMethod
     */
    '3dsUsed'?: boolean;
    /**
     * Indication of 2fa being used.
     * @type {boolean}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantPaymentMethod
     */
    '2faUsed'?: boolean;
}

