/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApplicantAddConsentToProfileRequestRecordsInner } from './applicant-add-consent-to-profile-request-records-inner';

/**
 * 
 * @export
 * @interface ApplicantAddConsentToProfileRequest1
 */
export interface ApplicantAddConsentToProfileRequest1 {
    /**
     * An array of applicant consents.
     * @type {Array<ApplicantAddConsentToProfileRequestRecordsInner>}
     * @memberof ApplicantAddConsentToProfileRequest1
     */
    'records': Array<ApplicantAddConsentToProfileRequestRecordsInner>;
    /**
     * Date and time a consent was accepted by the applicant.
     * @type {string}
     * @memberof ApplicantAddConsentToProfileRequest1
     */
    'acceptedAt'?: string;
    /**
     * An applicant country of residence.
     * @type {string}
     * @memberof ApplicantAddConsentToProfileRequest1
     */
    'residenceCountry'?: string;
}

