/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApplicantSubmitTransactionDataRequestApplicantDeviceAddress } from './applicant-submit-transaction-data-request-applicant-device-address';
import { ApplicantSubmitTransactionDataRequestApplicantDeviceCoords } from './applicant-submit-transaction-data-request-applicant-device-coords';
import { ApplicantSubmitTransactionDataRequestApplicantDeviceIpInfo } from './applicant-submit-transaction-data-request-applicant-device-ip-info';

/**
 * Device information.
 * @export
 * @interface ApplicantSubmitTransactionDataRequestApplicantDevice
 */
export interface ApplicantSubmitTransactionDataRequestApplicantDevice {
    /**
     * Device user agent.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantDevice
     */
    'userAgent'?: string;
    /**
     * Transaction session identifier.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantDevice
     */
    'sessionId'?: string;
    /**
     * Session lifetime in milliseconds.
     * @type {number}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantDevice
     */
    'sessionAgeMs'?: number;
    /**
     * From browser, e.g. `en`.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantDevice
     */
    'acceptLang'?: string;
    /**
     * Device platform, e.g. `Mobile Android`.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantDevice
     */
    'platform'?: string;
    /**
     * Device fingerprint.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantDevice
     */
    'fingerprint'?: string;
    /**
     * 
     * @type {ApplicantSubmitTransactionDataRequestApplicantDeviceAddress}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantDevice
     */
    'address'?: ApplicantSubmitTransactionDataRequestApplicantDeviceAddress;
    /**
     * 
     * @type {ApplicantSubmitTransactionDataRequestApplicantDeviceCoords}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantDevice
     */
    'coords'?: ApplicantSubmitTransactionDataRequestApplicantDeviceCoords;
    /**
     * 
     * @type {ApplicantSubmitTransactionDataRequestApplicantDeviceIpInfo}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantDevice
     */
    'ipInfo'?: ApplicantSubmitTransactionDataRequestApplicantDeviceIpInfo;
}

