/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApplicantUpdateFixedInfoRequest
 */
export interface ApplicantUpdateFixedInfoRequest {
    /**
     * The first name of the applicant.
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'firstName'?: string;
    /**
     * The last name of the applicant.
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'lastName'?: string;
    /**
     * The middle name of the applicant.
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'middleName'?: string;
    /**
     * Automatic transliteration of the first name.
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'firstNameEn'?: string;
    /**
     * Automatic transliteration of the last name.
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'lastNameEn'?: string;
    /**
     * Automatic transliteration of the middle name.
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'middleNameEn'?: string;
    /**
     * Legal name.
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'legalName'?: string;
    /**
     * An applicant gender (`M` or `F`).
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'gender'?: string;
    /**
     * Applicant date of birth (format `YYYY-mm-dd`, e.g. 2001-09-25).
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'dob'?: string;
    /**
     * The applicant birthplace.
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'placeOfBirth'?: string;
    /**
     * Applicant country of birth.
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'countryOfBirth'?: string;
    /**
     * Applicant state of birth.
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'stateOfBirth'?: string;
    /**
     * Alpha-3 country code (e.g. `DEU` or `GBR`).
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'country'?: string;
    /**
     * Alpha-3 country code.
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'nationality'?: string;
    /**
     * List of applicant addresses.
     * @type {Array<any>}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'addresses'?: Array<any>;
    /**
     * Tax identification number.
     * @type {string}
     * @memberof ApplicantUpdateFixedInfoRequest
     */
    'tin'?: string;
}

