/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Participant address.
 * @export
 * @interface ApplicantSubmitTransactionDataRequestApplicantAddress
 */
export interface ApplicantSubmitTransactionDataRequestApplicantAddress {
    /**
     * Alpha-3 country code.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantAddress
     */
    'country'?: string;
    /**
     * Postal code.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantAddress
     */
    'postCode'?: string;
    /**
     * Town or city name.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantAddress
     */
    'town'?: string;
    /**
     * Street name.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantAddress
     */
    'street'?: string;
    /**
     * Additional street information.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantAddress
     */
    'subStreet'?: string;
    /**
     * State name (if applicable).
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantAddress
     */
    'state'?: string;
    /**
     * Building name (if applicable).
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantAddress
     */
    'buildingName'?: string;
    /**
     * Flat or apartment number.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantAddress
     */
    'flatNumber'?: string;
    /**
     * Building number.
     * @type {string}
     * @memberof ApplicantSubmitTransactionDataRequestApplicantAddress
     */
    'buildingNumber'?: string;
}

