/*
Sumsub API

Sumsub is the one verification platform to secure the whole user journey. With Sumsub's customizable KYC, KYB, transaction monitoring and fraud prevention solutions, you can orchestrate your verification process, welcome more customers worldwide, meet compliance requirements, reduce costs and protect your business.

Sumsub has over 2,000 clients in fintech, crypto, transportation, trading, e-commerce and gaming industries including Binance, Wirex, Avis, Bybit, Huobi, Unlimit, Flutter, Kaizen Gaming, and TransferGo.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransactionBulkImportRequestDataApplicant } from './transaction-bulk-import-request-data-applicant';
import { TransactionBulkImportRequestDataCounterparty } from './transaction-bulk-import-request-data-counterparty';
import { TransactionBulkImportRequestDataInfo } from './transaction-bulk-import-request-data-info';

/**
 * An object representing the transaction. For more information on the structure, see [Submit transaction for existing applicant](ref:submit-transaction-for-existing-applicant).
 * @export
 * @interface TransactionBulkImportRequestData
 */
export interface TransactionBulkImportRequestData {
    /**
     * 
     * @type {TransactionBulkImportRequestDataInfo}
     * @memberof TransactionBulkImportRequestData
     */
    'info'?: TransactionBulkImportRequestDataInfo;
    /**
     * A unique transaction identifier.
     * @type {string}
     * @memberof TransactionBulkImportRequestData
     */
    'txnId': string;
    /**
     * Time when the transaction was initiated (format `yyyy-MM-dd HH:mm:ss+XXXX`, e.g. 2022-11-24 23:37:02+0000).
     * @type {string}
     * @memberof TransactionBulkImportRequestData
     */
    'txnDate'?: string;
    /**
     * Transaction properties. Map of strings - JSON of custom keys and string values.
     * @type {string}
     * @memberof TransactionBulkImportRequestData
     */
    'props'?: string;
    /**
     * 
     * @type {TransactionBulkImportRequestDataApplicant}
     * @memberof TransactionBulkImportRequestData
     */
    'applicant'?: TransactionBulkImportRequestDataApplicant;
    /**
     * 
     * @type {TransactionBulkImportRequestDataCounterparty}
     * @memberof TransactionBulkImportRequestData
     */
    'counterparty'?: TransactionBulkImportRequestDataCounterparty;
    /**
     * Transaction type. Takes predefined values: `finance`/`gamblingBet`/`gamblingLimitChange`/`kyc`/`login`/`signup`/`passwordChange`/`twoFaReset`/`travelRule` (`finance` by default).
     * @type {string}
     * @memberof TransactionBulkImportRequestData
     */
    'type'?: string;
    /**
     * Source Key indication to separate accesses to transactions.
     * @type {string}
     * @memberof TransactionBulkImportRequestData
     */
    'sourceKey'?: string;
}

